### ISSUE TITLE
release

### ISSUE THREAD

**Issue by Marco-cefetmg** [cisoun/Thereminoid#1]
Can anyone add a release? I dont have Android studio

**Comment by cisoun** [comment]
Hi ! I'll see if can, and I'm still planning to do it, but not right away. I have a lot of things going on these days and don't have much time. Sorry for that...
I hope someone could do it until I'm done with my stuff.

**Comment by cisoun** [comment]
Hi ! Due to certain circumstances, I had to rebuild this project so I published an APK in the releases if you're still interested. Some old remaining bugs may occur though but the app should work fine.
